type DestinationData = {
  [key: string]: {
    description: string;
    weather: { [key: string]: { high_temp: number; rain: number } };
  };
};

let DestinationWeather: DestinationData = {
  "Bangkok, Thailand": {
    description:
      "A thrilling city of golden temples, floating markets, and bustling street food stalls.",
    weather: {
      January: { high_temp: 89, rain: 1 },
      February: { high_temp: 90, rain: 2 },
      March: { high_temp: 92, rain: 4 },
      April: { high_temp: 94, rain: 8 },
      May: { high_temp: 92, rain: 16 },
      June: { high_temp: 91, rain: 16 },
      July: { high_temp: 91, rain: 17 },
      August: { high_temp: 91, rain: 18 },
      September: { high_temp: 90, rain: 19 },
      October: { high_temp: 90, rain: 15 },
      November: { high_temp: 89, rain: 5 },
      December: { high_temp: 87, rain: 1 },
    },
  },
  "Shanghai, China": {
    description:
      "A dazzling financial hub with futuristic skyscrapers, colonial Bund architecture, and historic temples.",
    weather: {
      January: { high_temp: 44, rain: 10 },
      February: { high_temp: 46, rain: 8 },
      March: { high_temp: 53, rain: 9 },
      April: { high_temp: 62, rain: 8 },
      May: { high_temp: 71, rain: 7 },
      June: { high_temp: 80, rain: 12 },
      July: { high_temp: 86, rain: 14 },
      August: { high_temp: 85, rain: 14 },
      September: { high_temp: 78, rain: 13 },
      October: { high_temp: 66, rain: 10 },
      November: { high_temp: 54, rain: 9 },
      December: { high_temp: 46, rain: 10 },
    },
  },
  "Montreal, Canada": {
    description:
      "A vibrant blend of European charm and modern culture, known for its festivals, food, and historic Old Town.",
    weather: {
      January: { high_temp: 22, rain: 11 },
      February: { high_temp: 24, rain: 8 },
      March: { high_temp: 34, rain: 9 },
      April: { high_temp: 45, rain: 8 },
      May: { high_temp: 59, rain: 8 },
      June: { high_temp: 70, rain: 9 },
      July: { high_temp: 75, rain: 8 },
      August: { high_temp: 73, rain: 9 },
      September: { high_temp: 63, rain: 9 },
      October: { high_temp: 50, rain: 9 },
      November: { high_temp: 34, rain: 10 },
      December: { high_temp: 24, rain: 11 },
    },
  },
  "Dubrovnik, Croatia": {
    description:
      "A medieval coastal city with stunning sea views, historic walls, and a Game of Thrones connection.",
    weather: {
      January: { high_temp: 55, rain: 8 },
      February: { high_temp: 57, rain: 7 },
      March: { high_temp: 61, rain: 8 },
      April: { high_temp: 66, rain: 7 },
      May: { high_temp: 74, rain: 6 },
      June: { high_temp: 80, rain: 4 },
      July: { high_temp: 85, rain: 2 },
      August: { high_temp: 85, rain: 3 },
      September: { high_temp: 79, rain: 5 },
      October: { high_temp: 68, rain: 8 },
      November: { high_temp: 60, rain: 9 },
      December: { high_temp: 55, rain: 8 },
    },
  },
  "St. Petersburg, Russia": {
    description:
      "A city of imperial palaces, grand canals, and a rich cultural and artistic legacy.",
    weather: {
      January: { high_temp: 21, rain: 18 },
      February: { high_temp: 23, rain: 16 },
      March: { high_temp: 30, rain: 16 },
      April: { high_temp: 42, rain: 14 },
      May: { high_temp: 50, rain: 12 },
      June: { high_temp: 55, rain: 10 },
      July: { high_temp: 58, rain: 9 },
      August: { high_temp: 57, rain: 9 },
      September: { high_temp: 50, rain: 13 },
      October: { high_temp: 41, rain: 15 },
      November: { high_temp: 35, rain: 17 },
      December: { high_temp: 34, rain: 18 },
    },
  },
  "Seoul, South Korea": {
    description:
      "A dynamic city where ancient palaces meet K-pop culture, high-tech innovation, and mouthwatering Korean cuisine.",
    weather: {
      January: { high_temp: 35, rain: 6 },
      February: { high_temp: 40, rain: 5 },
      March: { high_temp: 51, rain: 7 },
      April: { high_temp: 64, rain: 7 },
      May: { high_temp: 74, rain: 8 },
      June: { high_temp: 81, rain: 9 },
      July: { high_temp: 85, rain: 15 },
      August: { high_temp: 87, rain: 13 },
      September: { high_temp: 78, rain: 9 },
      October: { high_temp: 67, rain: 6 },
      November: { high_temp: 52, rain: 6 },
      December: { high_temp: 39, rain: 7 },
    },
  },
  "Moscow, Russia": {
    description:
      "A city of iconic architecture, from the Kremlin to Red Square, with a deep cultural heritage.",
    weather: {
      January: { high_temp: 24, rain: 8 },
      February: { high_temp: 27, rain: 7 },
      March: { high_temp: 38, rain: 8 },
      April: { high_temp: 52, rain: 9 },
      May: { high_temp: 66, rain: 10 },
      June: { high_temp: 73, rain: 10 },
      July: { high_temp: 77, rain: 9 },
      August: { high_temp: 75, rain: 9 },
      September: { high_temp: 63, rain: 9 },
      October: { high_temp: 50, rain: 9 },
      November: { high_temp: 35, rain: 9 },
      December: { high_temp: 27, rain: 9 },
    },
  },
  "Toronto, Canada": {
    description:
      "A diverse metropolis with a stunning skyline, world-class museums, and vibrant neighborhoods.",
    weather: {
      January: { high_temp: 30, rain: 10 },
      February: { high_temp: 32, rain: 9 },
      March: { high_temp: 41, rain: 9 },
      April: { high_temp: 54, rain: 10 },
      May: { high_temp: 66, rain: 11 },
      June: { high_temp: 75, rain: 9 },
      July: { high_temp: 81, rain: 8 },
      August: { high_temp: 79, rain: 8 },
      September: { high_temp: 72, rain: 9 },
      October: { high_temp: 58, rain: 10 },
      November: { high_temp: 46, rain: 11 },
      December: { high_temp: 34, rain: 11 },
    },
  },
  "Phnom Penh, Cambodia": {
    description:
      "A city of temples, markets, and a rich culinary scene, with a tragic history to explore.",
    weather: {
      January: { high_temp: 88, rain: 0 },
      February: { high_temp: 89, rain: 0 },
      March: { high_temp: 91, rain: 1 },
      April: { high_temp: 92, rain: 4 },
      May: { high_temp: 91, rain: 9 },
      June: { high_temp: 90, rain: 14 },
      July: { high_temp: 89, rain: 16 },
      August: { high_temp: 89, rain: 15 },
      September: { high_temp: 88, rain: 17 },
      October: { high_temp: 88, rain: 13 },
      November: { high_temp: 88, rain: 4 },
      December: { high_temp: 88, rain: 1 },
    },
  },
  "New Delhi, India": {
    description:
      "A cultural powerhouse with Mughal-era landmarks, colorful bazaars, and historic sites like the Red Fort.",
    weather: {
      January: { high_temp: 68, rain: 2 },
      February: { high_temp: 74, rain: 2 },
      March: { high_temp: 84, rain: 2 },
      April: { high_temp: 96, rain: 2 },
      May: { high_temp: 104, rain: 4 },
      June: { high_temp: 102, rain: 7 },
      July: { high_temp: 95, rain: 12 },
      August: { high_temp: 92, rain: 12 },
      September: { high_temp: 91, rain: 8 },
      October: { high_temp: 89, rain: 2 },
      November: { high_temp: 80, rain: 1 },
      December: { high_temp: 71, rain: 1 },
    },
  },
  "Grand Canyon National Park, USA": {
    description:
      "A natural wonder of red rock canyons, stunning vistas, and outdoor adventures.",
    weather: {
      January: { high_temp: 44, rain: 5 },
      February: { high_temp: 47, rain: 4 },
      March: { high_temp: 56, rain: 5 },
      April: { high_temp: 64, rain: 5 },
      May: { high_temp: 73, rain: 4 },
      June: { high_temp: 85, rain: 2 },
      July: { high_temp: 89, rain: 9 },
      August: { high_temp: 87, rain: 10 },
      September: { high_temp: 81, rain: 6 },
      October: { high_temp: 68, rain: 4 },
      November: { high_temp: 53, rain: 5 },
      December: { high_temp: 45, rain: 5 },
    },
  },
  "Santiago, Chile": {
    description:
      "A dynamic metropolis surrounded by the Andes, offering world-class wine, culture, and outdoor adventures.",
    weather: {
      January: { high_temp: 87, rain: 2 },
      February: { high_temp: 88, rain: 1 },
      March: { high_temp: 85, rain: 2 },
      April: { high_temp: 75, rain: 5 },
      May: { high_temp: 66, rain: 8 },
      June: { high_temp: 60, rain: 11 },
      July: { high_temp: 59, rain: 12 },
      August: { high_temp: 60, rain: 10 },
      September: { high_temp: 67, rain: 6 },
      October: { high_temp: 74, rain: 3 },
      November: { high_temp: 79, rain: 2 },
      December: { high_temp: 84, rain: 1 },
    },
  },
  "Seattle, Washington, USA": {
    description:
      "A waterfront city known for coffee culture, tech innovation, and stunning mountain views.",
    weather: {
      January: { high_temp: 46, rain: 18 },
      February: { high_temp: 48, rain: 14 },
      March: { high_temp: 51, rain: 15 },
      April: { high_temp: 57, rain: 14 },
      May: { high_temp: 64, rain: 10 },
      June: { high_temp: 70, rain: 7 },
      July: { high_temp: 75, rain: 4 },
      August: { high_temp: 75, rain: 4 },
      September: { high_temp: 69, rain: 7 },
      October: { high_temp: 57, rain: 14 },
      November: { high_temp: 48, rain: 17 },
      December: { high_temp: 45, rain: 18 },
    },
  },
  "Madrid, Spain": {
    description:
      "A city bursting with royal palaces, world-class museums, and a lively food and nightlife scene.",
    weather: {
      January: { high_temp: 52, rain: 7 },
      February: { high_temp: 55, rain: 6 },
      March: { high_temp: 61, rain: 7 },
      April: { high_temp: 66, rain: 8 },
      May: { high_temp: 73, rain: 5 },
      June: { high_temp: 81, rain: 2 },
      July: { high_temp: 91, rain: 0 },
      August: { high_temp: 90, rain: 0 },
      September: { high_temp: 81, rain: 2 },
      October: { high_temp: 70, rain: 6 },
      November: { high_temp: 59, rain: 7 },
      December: { high_temp: 52, rain: 7 },
    },
  },
  "Athens, Greece": {
    description:
      "The birthplace of democracy, filled with ancient ruins, vibrant neighborhoods, and delicious Mediterranean cuisine.",
    weather: {
      January: { high_temp: 55, rain: 10 },
      February: { high_temp: 57, rain: 9 },
      March: { high_temp: 61, rain: 8 },
      April: { high_temp: 68, rain: 6 },
      May: { high_temp: 77, rain: 4 },
      June: { high_temp: 85, rain: 2 },
      July: { high_temp: 91, rain: 1 },
      August: { high_temp: 90, rain: 1 },
      September: { high_temp: 83, rain: 2 },
      October: { high_temp: 73, rain: 6 },
      November: { high_temp: 64, rain: 8 },
      December: { high_temp: 57, rain: 10 },
    },
  },
  "Bali, Indonesia": {
    description:
      "A tropical paradise of lush jungles, stunning beaches, and a vibrant spiritual culture.",
    weather: {
      January: { high_temp: 88, rain: 19 },
      February: { high_temp: 88, rain: 18 },
      March: { high_temp: 88, rain: 17 },
      April: { high_temp: 88, rain: 14 },
      May: { high_temp: 87, rain: 12 },
      June: { high_temp: 86, rain: 8 },
      July: { high_temp: 86, rain: 7 },
      August: { high_temp: 86, rain: 7 },
      September: { high_temp: 87, rain: 9 },
      October: { high_temp: 87, rain: 12 },
      November: { high_temp: 88, rain: 16 },
      December: { high_temp: 88, rain: 19 },
    },
  },
  "Belgrade, Serbia": {
    description:
      "A vibrant Balkan capital known for its rich history, lively nightlife, and stunning riverside views.",
    weather: {
      January: { high_temp: 39, rain: 7 },
      February: { high_temp: 42, rain: 7 },
      March: { high_temp: 50, rain: 9 },
      April: { high_temp: 61, rain: 8 },
      May: { high_temp: 70, rain: 8 },
      June: { high_temp: 77, rain: 7 },
      July: { high_temp: 84, rain: 6 },
      August: { high_temp: 84, rain: 5 },
      September: { high_temp: 75, rain: 6 },
      October: { high_temp: 61, rain: 7 },
      November: { high_temp: 50, rain: 8 },
      December: { high_temp: 40, rain: 7 },
    },
  },
  "Amman, Jordan": {
    description:
      "A city steeped in history, from Roman ruins to bustling souks and a gateway to Petra.",
    weather: {
      January: { high_temp: 55, rain: 7 },
      February: { high_temp: 56, rain: 7 },
      March: { high_temp: 61, rain: 6 },
      April: { high_temp: 70, rain: 4 },
      May: { high_temp: 77, rain: 2 },
      June: { high_temp: 86, rain: 0 },
      July: { high_temp: 92, rain: 0 },
      August: { high_temp: 91, rain: 0 },
      September: { high_temp: 85, rain: 1 },
      October: { high_temp: 75, rain: 4 },
      November: { high_temp: 64, rain: 6 },
      December: { high_temp: 57, rain: 7 },
    },
  },
  "Lagos, Nigeria": {
    description:
      "A fast-paced city known for its music scene, vibrant markets, and energetic culture.",
    weather: {
      January: { high_temp: 89, rain: 2 },
      February: { high_temp: 90, rain: 1 },
      March: { high_temp: 90, rain: 3 },
      April: { high_temp: 89, rain: 5 },
      May: { high_temp: 88, rain: 15 },
      June: { high_temp: 85, rain: 20 },
      July: { high_temp: 83, rain: 23 },
      August: { high_temp: 83, rain: 22 },
      September: { high_temp: 83, rain: 21 },
      October: { high_temp: 85, rain: 18 },
      November: { high_temp: 87, rain: 7 },
      December: { high_temp: 88, rain: 3 },
    },
  },
  "Jakarta, Indonesia": {
    description:
      "Indonesia's energetic capital, offering a mix of historical sites, shopping, and a gateway to nearby tropical escapes.",
    weather: {
      January: { high_temp: 86, rain: 17 },
      February: { high_temp: 87, rain: 16 },
      March: { high_temp: 88, rain: 17 },
      April: { high_temp: 89, rain: 13 },
      May: { high_temp: 90, rain: 11 },
      June: { high_temp: 89, rain: 9 },
      July: { high_temp: 89, rain: 7 },
      August: { high_temp: 89, rain: 7 },
      September: { high_temp: 90, rain: 8 },
      October: { high_temp: 90, rain: 11 },
      November: { high_temp: 89, rain: 14 },
      December: { high_temp: 87, rain: 16 },
    },
  },
  "Los Angeles, USA": {
    description:
      "A star-studded city with beautiful beaches, iconic landmarks, and a thriving entertainment scene.",
    weather: {
      January: { high_temp: 68, rain: 6 },
      February: { high_temp: 69, rain: 6 },
      March: { high_temp: 70, rain: 5 },
      April: { high_temp: 73, rain: 2 },
      May: { high_temp: 74, rain: 1 },
      June: { high_temp: 79, rain: 0 },
      July: { high_temp: 84, rain: 0 },
      August: { high_temp: 85, rain: 0 },
      September: { high_temp: 83, rain: 0 },
      October: { high_temp: 78, rain: 1 },
      November: { high_temp: 73, rain: 2 },
      December: { high_temp: 68, rain: 5 },
    },
  },
  "Mumbai, India": {
    description:
      "India's entertainment and financial capital, boasting colonial architecture, Bollywood glamour, and street food delights.",
    weather: {
      January: { high_temp: 86, rain: 1 },
      February: { high_temp: 88, rain: 1 },
      March: { high_temp: 90, rain: 1 },
      April: { high_temp: 91, rain: 2 },
      May: { high_temp: 90, rain: 5 },
      June: { high_temp: 88, rain: 14 },
      July: { high_temp: 85, rain: 15 },
      August: { high_temp: 85, rain: 15 },
      September: { high_temp: 86, rain: 14 },
      October: { high_temp: 88, rain: 5 },
      November: { high_temp: 88, rain: 2 },
      December: { high_temp: 86, rain: 1 },
    },
  },
  "Manila, Philippines": {
    description:
      "A bustling capital blending Spanish colonial history with modern skyscrapers, lively street markets, and stunning bay sunsets.",
    weather: {
      January: { high_temp: 86, rain: 5 },
      February: { high_temp: 87, rain: 3 },
      March: { high_temp: 90, rain: 5 },
      April: { high_temp: 93, rain: 6 },
      May: { high_temp: 94, rain: 14 },
      June: { high_temp: 91, rain: 17 },
      July: { high_temp: 88, rain: 22 },
      August: { high_temp: 88, rain: 22 },
      September: { high_temp: 88, rain: 19 },
      October: { high_temp: 88, rain: 16 },
      November: { high_temp: 87, rain: 10 },
      December: { high_temp: 86, rain: 7 },
    },
  },
  "Budapest, Hungary": {
    description:
      "A stunning city of thermal baths, grand architecture, and Danube River views.",
    weather: {
      January: { high_temp: 36, rain: 8 },
      February: { high_temp: 39, rain: 7 },
      March: { high_temp: 48, rain: 9 },
      April: { high_temp: 58, rain: 9 },
      May: { high_temp: 66, rain: 8 },
      June: { high_temp: 73, rain: 7 },
      July: { high_temp: 78, rain: 7 },
      August: { high_temp: 77, rain: 7 },
      September: { high_temp: 69, rain: 7 },
      October: { high_temp: 58, rain: 9 },
      November: { high_temp: 46, rain: 9 },
      December: { high_temp: 39, rain: 9 },
    },
  },
  "Tenerife, Spain": {
    description:
      "A Spanish island with volcanic landscapes, black sand beaches, and charming villages.",
    weather: {
      January: { high_temp: 68, rain: 5 },
      February: { high_temp: 69, rain: 5 },
      March: { high_temp: 71, rain: 4 },
      April: { high_temp: 73, rain: 4 },
      May: { high_temp: 75, rain: 3 },
      June: { high_temp: 77, rain: 2 },
      July: { high_temp: 79, rain: 1 },
      August: { high_temp: 80, rain: 1 },
      September: { high_temp: 79, rain: 2 },
      October: { high_temp: 76, rain: 3 },
      November: { high_temp: 71, rain: 4 },
      December: { high_temp: 69, rain: 5 },
    },
  },
  "Seville, Spain": {
    description:
      "A sun-drenched city of flamenco, Moorish palaces, and lively tapas bars.",
    weather: {
      January: { high_temp: 56, rain: 6 },
      February: { high_temp: 59, rain: 5 },
      March: { high_temp: 64, rain: 6 },
      April: { high_temp: 70, rain: 4 },
      May: { high_temp: 77, rain: 3 },
      June: { high_temp: 88, rain: 1 },
      July: { high_temp: 97, rain: 0 },
      August: { high_temp: 96, rain: 0 },
      September: { high_temp: 86, rain: 2 },
      October: { high_temp: 75, rain: 4 },
      November: { high_temp: 64, rain: 6 },
      December: { high_temp: 57, rain: 6 },
    },
  },
  "Ulaanbaatar, Mongolia": {
    description:
      "A city of nomadic culture, Buddhist temples, and access to the vast Mongolian steppe.",
    weather: {
      January: { high_temp: -10, rain: 1 },
      February: { high_temp: -8, rain: 1 },
      March: { high_temp: -2, rain: 1 },
      April: { high_temp: 7, rain: 2 },
      May: { high_temp: 15, rain: 4 },
      June: { high_temp: 21, rain: 6 },
      July: { high_temp: 24, rain: 8 },
      August: { high_temp: 21, rain: 7 },
      September: { high_temp: 13, rain: 4 },
      October: { high_temp: 4, rain: 2 },
      November: { high_temp: -4, rain: 1 },
      December: { high_temp: -9, rain: 1 },
    },
  },
  "Auckland, New Zealand": {
    description:
      "A lively city surrounded by volcanic landscapes and beautiful harbors.",
    weather: {
      January: { high_temp: 72, rain: 10 },
      February: { high_temp: 73, rain: 9 },
      March: { high_temp: 72, rain: 9 },
      April: { high_temp: 66, rain: 10 },
      May: { high_temp: 59, rain: 11 },
      June: { high_temp: 54, rain: 12 },
      July: { high_temp: 54, rain: 12 },
      August: { high_temp: 55, rain: 12 },
      September: { high_temp: 59, rain: 11 },
      October: { high_temp: 64, rain: 10 },
      November: { high_temp: 68, rain: 9 },
      December: { high_temp: 71, rain: 9 },
    },
  },
  "Marrakech, Morocco": {
    description:
      "A city of vibrant souks, historic palaces, and exotic desert landscapes.",
    weather: {
      January: { high_temp: 66, rain: 5 },
      February: { high_temp: 69, rain: 4 },
      March: { high_temp: 74, rain: 5 },
      April: { high_temp: 77, rain: 5 },
      May: { high_temp: 83, rain: 3 },
      June: { high_temp: 91, rain: 1 },
      July: { high_temp: 98, rain: 0 },
      August: { high_temp: 97, rain: 0 },
      September: { high_temp: 91, rain: 1 },
      October: { high_temp: 82, rain: 4 },
      November: { high_temp: 73, rain: 4 },
      December: { high_temp: 66, rain: 5 },
    },
  },
  "Miami, Florida, USA": {
    description:
      "A sun-soaked destination with beautiful beaches, Latin culture, and a thriving nightlife.",
    weather: {
      January: { high_temp: 74, rain: 7 },
      February: { high_temp: 75, rain: 6 },
      March: { high_temp: 77, rain: 6 },
      April: { high_temp: 79, rain: 5 },
      May: { high_temp: 83, rain: 8 },
      June: { high_temp: 88, rain: 13 },
      July: { high_temp: 90, rain: 15 },
      August: { high_temp: 90, rain: 15 },
      September: { high_temp: 88, rain: 14 },
      October: { high_temp: 83, rain: 11 },
      November: { high_temp: 78, rain: 8 },
      December: { high_temp: 75, rain: 6 },
    },
  },
  "San Jose, Costa Rica": {
    description:
      "A lively city surrounded by lush rainforests, volcanoes, and incredible wildlife.",
    weather: {
      January: { high_temp: 74, rain: 2 },
      February: { high_temp: 75, rain: 2 },
      March: { high_temp: 77, rain: 3 },
      April: { high_temp: 78, rain: 6 },
      May: { high_temp: 77, rain: 14 },
      June: { high_temp: 76, rain: 16 },
      July: { high_temp: 76, rain: 14 },
      August: { high_temp: 76, rain: 15 },
      September: { high_temp: 76, rain: 17 },
      October: { high_temp: 76, rain: 16 },
      November: { high_temp: 75, rain: 12 },
      December: { high_temp: 74, rain: 7 },
    },
  },
  "Reykjavik, Iceland": {
    description:
      "A charming capital known for colorful houses, geothermal lagoons, and northern lights views.",
    weather: {
      January: { high_temp: 36, rain: 18 },
      February: { high_temp: 37, rain: 16 },
      March: { high_temp: 39, rain: 16 },
      April: { high_temp: 42, rain: 14 },
      May: { high_temp: 49, rain: 12 },
      June: { high_temp: 55, rain: 10 },
      July: { high_temp: 58, rain: 9 },
      August: { high_temp: 57, rain: 9 },
      September: { high_temp: 50, rain: 13 },
      October: { high_temp: 41, rain: 15 },
      November: { high_temp: 35, rain: 17 },
      December: { high_temp: 34, rain: 18 },
    },
  },
  "Havana, Cuba": {
    description:
      "A city of vintage cars, colonial architecture, and vibrant music-filled streets.",
    weather: {
      January: { high_temp: 79, rain: 5 },
      February: { high_temp: 80, rain: 4 },
      March: { high_temp: 82, rain: 4 },
      April: { high_temp: 85, rain: 6 },
      May: { high_temp: 87, rain: 10 },
      June: { high_temp: 89, rain: 14 },
      July: { high_temp: 90, rain: 14 },
      August: { high_temp: 90, rain: 14 },
      September: { high_temp: 89, rain: 14 },
      October: { high_temp: 86, rain: 11 },
      November: { high_temp: 83, rain: 7 },
      December: { high_temp: 80, rain: 5 },
    },
  },
  "Lisbon, Portugal": {
    description:
      "A sun-drenched city of trams, tiled facades, and stunning coastal views.",
    weather: {
      January: { high_temp: 58, rain: 10 },
      February: { high_temp: 60, rain: 9 },
      March: { high_temp: 63, rain: 9 },
      April: { high_temp: 66, rain: 7 },
      May: { high_temp: 70, rain: 6 },
      June: { high_temp: 77, rain: 3 },
      July: { high_temp: 82, rain: 1 },
      August: { high_temp: 83, rain: 1 },
      September: { high_temp: 80, rain: 3 },
      October: { high_temp: 72, rain: 7 },
      November: { high_temp: 64, rain: 9 },
      December: { high_temp: 59, rain: 11 },
    },
  },
  "Oslo, Norway": {
    description:
      "A modern capital surrounded by fjords, featuring Viking history, cutting-edge design, and outdoor adventure.",
    weather: {
      January: { high_temp: 30, rain: 10 },
      February: { high_temp: 32, rain: 9 },
      March: { high_temp: 40, rain: 9 },
      April: { high_temp: 51, rain: 8 },
      May: { high_temp: 62, rain: 9 },
      June: { high_temp: 70, rain: 10 },
      July: { high_temp: 75, rain: 11 },
      August: { high_temp: 72, rain: 11 },
      September: { high_temp: 62, rain: 10 },
      October: { high_temp: 50, rain: 10 },
      November: { high_temp: 39, rain: 10 },
      December: { high_temp: 32, rain: 10 },
    },
  },
  "Dubai, UAE": {
    description:
      "A futuristic desert city with record-breaking skyscrapers, luxury shopping, and thrilling desert adventures.",
    weather: {
      January: { high_temp: 75, rain: 2 },
      February: { high_temp: 77, rain: 2 },
      March: { high_temp: 82, rain: 2 },
      April: { high_temp: 90, rain: 1 },
      May: { high_temp: 99, rain: 0 },
      June: { high_temp: 104, rain: 0 },
      July: { high_temp: 106, rain: 0 },
      August: { high_temp: 106, rain: 0 },
      September: { high_temp: 102, rain: 0 },
      October: { high_temp: 95, rain: 0 },
      November: { high_temp: 86, rain: 1 },
      December: { high_temp: 77, rain: 2 },
    },
  },
  "Rio de Janeiro, Brazil": {
    description:
      "A city of samba, stunning beaches, and the iconic Christ the Redeemer statue.",
    weather: {
      January: { high_temp: 86, rain: 15 },
      February: { high_temp: 86, rain: 14 },
      March: { high_temp: 86, rain: 13 },
      April: { high_temp: 84, rain: 12 },
      May: { high_temp: 81, rain: 8 },
      June: { high_temp: 79, rain: 6 },
      July: { high_temp: 78, rain: 6 },
      August: { high_temp: 79, rain: 5 },
      September: { high_temp: 81, rain: 8 },
      October: { high_temp: 83, rain: 9 },
      November: { high_temp: 84, rain: 12 },
      December: { high_temp: 86, rain: 13 },
    },
  },
  "Milan, Italy": {
    description:
      "A fashion and design capital with grand architecture, elegant shopping streets, and rich history.",
    weather: {
      January: { high_temp: 43, rain: 8 },
      February: { high_temp: 46, rain: 7 },
      March: { high_temp: 54, rain: 9 },
      April: { high_temp: 61, rain: 10 },
      May: { high_temp: 70, rain: 8 },
      June: { high_temp: 77, rain: 6 },
      July: { high_temp: 84, rain: 4 },
      August: { high_temp: 83, rain: 4 },
      September: { high_temp: 74, rain: 7 },
      October: { high_temp: 59, rain: 9 },
      November: { high_temp: 50, rain: 9 },
      December: { high_temp: 44, rain: 8 },
    },
  },
  "Barcelona, Spain": {
    description:
      "A city of Gaudí's masterpieces, golden beaches, and a thriving culinary scene.",
    weather: {
      January: { high_temp: 57, rain: 4 },
      February: { high_temp: 59, rain: 4 },
      March: { high_temp: 61, rain: 5 },
      April: { high_temp: 65, rain: 6 },
      May: { high_temp: 70, rain: 5 },
      June: { high_temp: 77, rain: 4 },
      July: { high_temp: 82, rain: 2 },
      August: { high_temp: 82, rain: 4 },
      September: { high_temp: 78, rain: 5 },
      October: { high_temp: 72, rain: 6 },
      November: { high_temp: 63, rain: 5 },
      December: { high_temp: 57, rain: 4 },
    },
  },
  "New York City, USA": {
    description:
      "The city that never sleeps, filled with iconic landmarks, Broadway, and endless experiences.",
    weather: {
      January: { high_temp: 40, rain: 7.3 },
      February: { high_temp: 42, rain: 6.7 },
      March: { high_temp: 51, rain: 8.3 },
      April: { high_temp: 61, rain: 8.6 },
      May: { high_temp: 71, rain: 9.7 },
      June: { high_temp: 79, rain: 9.9 },
      July: { high_temp: 84, rain: 10.3 },
      August: { high_temp: 82, rain: 9.7 },
      September: { high_temp: 75, rain: 7.8 },
      October: { high_temp: 65, rain: 7.4 },
      November: { high_temp: 54, rain: 7.2 },
      December: { high_temp: 45, rain: 6.7 },
    },
  },
  "Prague, Czech Republic": {
    description:
      "A fairy-tale city of medieval streets, grand castles, and legendary beer culture.",
    weather: {
      January: { high_temp: 36, rain: 9 },
      February: { high_temp: 40, rain: 8 },
      March: { high_temp: 50, rain: 9 },
      April: { high_temp: 58, rain: 8 },
      May: { high_temp: 67, rain: 10 },
      June: { high_temp: 72, rain: 10 },
      July: { high_temp: 77, rain: 9 },
      August: { high_temp: 76, rain: 9 },
      September: { high_temp: 67, rain: 8 },
      October: { high_temp: 56, rain: 7 },
      November: { high_temp: 45, rain: 9 },
      December: { high_temp: 37, rain: 9 },
    },
  },
  "Panama City, Panama": {
    description:
      "A modern skyline meets historic charm, with the famous Panama Canal.",
    weather: {
      January: { high_temp: 88, rain: 11 },
      February: { high_temp: 89, rain: 8 },
      March: { high_temp: 89, rain: 8 },
      April: { high_temp: 90, rain: 9 },
      May: { high_temp: 90, rain: 15 },
      June: { high_temp: 90, rain: 17 },
      July: { high_temp: 89, rain: 16 },
      August: { high_temp: 89, rain: 17 },
      September: { high_temp: 88, rain: 18 },
      October: { high_temp: 88, rain: 18 },
      November: { high_temp: 88, rain: 14 },
      December: { high_temp: 88, rain: 12 },
    },
  },
  "San Juan, Puerto Rico": {
    description:
      "A tropical city with colorful colonial streets, rich history, and beautiful beaches.",
    weather: {
      January: { high_temp: 83, rain: 9 },
      February: { high_temp: 83, rain: 7 },
      March: { high_temp: 84, rain: 7 },
      April: { high_temp: 85, rain: 7 },
      May: { high_temp: 86, rain: 11 },
      June: { high_temp: 87, rain: 14 },
      July: { high_temp: 88, rain: 14 },
      August: { high_temp: 88, rain: 13 },
      September: { high_temp: 88, rain: 14 },
      October: { high_temp: 87, rain: 15 },
      November: { high_temp: 85, rain: 10 },
      December: { high_temp: 83, rain: 8 },
    },
  },
  "Cape Town, South Africa": {
    description:
      "A breathtaking city where mountains meet the sea, with vibrant culture and wildlife.",
    weather: {
      January: { high_temp: 79, rain: 3 },
      February: { high_temp: 79, rain: 3 },
      March: { high_temp: 77, rain: 4 },
      April: { high_temp: 73, rain: 5 },
      May: { high_temp: 68, rain: 8 },
      June: { high_temp: 63, rain: 9 },
      July: { high_temp: 62, rain: 9 },
      August: { high_temp: 63, rain: 8 },
      September: { high_temp: 65, rain: 5 },
      October: { high_temp: 69, rain: 4 },
      November: { high_temp: 73, rain: 3 },
      December: { high_temp: 77, rain: 3 },
    },
  },
  "Honolulu, Hawaii, USA": {
    description:
      "A tropical haven with stunning beaches, volcanic landscapes, and rich Polynesian culture.",
    weather: {
      January: { high_temp: 79, rain: 13 },
      February: { high_temp: 79, rain: 13 },
      March: { high_temp: 80, rain: 12 },
      April: { high_temp: 81, rain: 11 },
      May: { high_temp: 82, rain: 9 },
      June: { high_temp: 84, rain: 5 },
      July: { high_temp: 85, rain: 3 },
      August: { high_temp: 86, rain: 3 },
      September: { high_temp: 86, rain: 5 },
      October: { high_temp: 85, rain: 8 },
      November: { high_temp: 82, rain: 11 },
      December: { high_temp: 80, rain: 13 },
    },
  },
  "Tirana, Albania": {
    description:
      "A colorful, up-and-coming city with lively cafes, Ottoman history, and a thriving arts scene.",
    weather: {
      January: { high_temp: 48, rain: 9 },
      February: { high_temp: 51, rain: 8 },
      March: { high_temp: 55, rain: 8 },
      April: { high_temp: 61, rain: 7 },
      May: { high_temp: 70, rain: 7 },
      June: { high_temp: 77, rain: 5 },
      July: { high_temp: 84, rain: 2 },
      August: { high_temp: 84, rain: 3 },
      September: { high_temp: 77, rain: 5 },
      October: { high_temp: 64, rain: 8 },
      November: { high_temp: 55, rain: 9 },
      December: { high_temp: 48, rain: 9 },
    },
  },
  "Geneva, Switzerland": {
    description:
      "A sophisticated city surrounded by mountains, known for diplomacy, luxury watches, and stunning lakeside views.",
    weather: {
      January: { high_temp: 38, rain: 11 },
      February: { high_temp: 41, rain: 9 },
      March: { high_temp: 48, rain: 9 },
      April: { high_temp: 55, rain: 8 },
      May: { high_temp: 64, rain: 8 },
      June: { high_temp: 72, rain: 7 },
      July: { high_temp: 77, rain: 7 },
      August: { high_temp: 76, rain: 7 },
      September: { high_temp: 67, rain: 8 },
      October: { high_temp: 54, rain: 9 },
      November: { high_temp: 45, rain: 10 },
      December: { high_temp: 39, rain: 11 },
    },
  },
  "Rome, Italy": {
    description:
      "The Eternal City, home to the Colosseum, Vatican City, and some of the best pasta in the world.",
    weather: {
      January: { high_temp: 54, rain: 7 },
      February: { high_temp: 57, rain: 7 },
      March: { high_temp: 61, rain: 8 },
      April: { high_temp: 66, rain: 7 },
      May: { high_temp: 73, rain: 6 },
      June: { high_temp: 81, rain: 4 },
      July: { high_temp: 87, rain: 2 },
      August: { high_temp: 87, rain: 3 },
      September: { high_temp: 80, rain: 5 },
      October: { high_temp: 71, rain: 7 },
      November: { high_temp: 61, rain: 9 },
      December: { high_temp: 54, rain: 8 },
    },
  },
  "Lima, Peru": {
    description:
      "A coastal city with world-renowned cuisine and access to ancient Incan sites.",
    weather: {
      January: { high_temp: 79, rain: 0 },
      February: { high_temp: 80, rain: 0 },
      March: { high_temp: 80, rain: 0 },
      April: { high_temp: 78, rain: 1 },
      May: { high_temp: 74, rain: 3 },
      June: { high_temp: 70, rain: 6 },
      July: { high_temp: 69, rain: 7 },
      August: { high_temp: 70, rain: 6 },
      September: { high_temp: 73, rain: 3 },
      October: { high_temp: 75, rain: 1 },
      November: { high_temp: 77, rain: 0 },
      December: { high_temp: 79, rain: 0 },
    },
  },
  "Male, Maldives": {
    description:
      "A tropical paradise of overwater bungalows, crystal-clear lagoons, and pristine white-sand beaches.",
    weather: {
      January: { high_temp: 87, rain: 14 },
      February: { high_temp: 88, rain: 12 },
      March: { high_temp: 88, rain: 12 },
      April: { high_temp: 88, rain: 14 },
      May: { high_temp: 87, rain: 18 },
      June: { high_temp: 86, rain: 20 },
      July: { high_temp: 86, rain: 19 },
      August: { high_temp: 86, rain: 19 },
      September: { high_temp: 86, rain: 18 },
      October: { high_temp: 86, rain: 16 },
      November: { high_temp: 86, rain: 14 },
      December: { high_temp: 86, rain: 14 },
    },
  },
  "Hanoi, Vietnam": {
    description:
      "A charming city where French colonial architecture meets historic pagodas and delicious Vietnamese cuisine.",
    weather: {
      January: { high_temp: 66, rain: 7 },
      February: { high_temp: 68, rain: 10 },
      March: { high_temp: 73, rain: 12 },
      April: { high_temp: 81, rain: 14 },
      May: { high_temp: 89, rain: 15 },
      June: { high_temp: 92, rain: 14 },
      July: { high_temp: 92, rain: 13 },
      August: { high_temp: 90, rain: 14 },
      September: { high_temp: 86, rain: 12 },
      October: { high_temp: 81, rain: 9 },
      November: { high_temp: 74, rain: 7 },
      December: { high_temp: 68, rain: 6 },
    },
  },
  "Kigali, Rwanda": {
    description:
      "A clean and vibrant capital surrounded by rolling hills, offering a rich cultural scene and access to Rwanda's famous gorilla trekking.",
    weather: {
      January: { high_temp: 80, rain: 4 },
      February: { high_temp: 81, rain: 5 },
      March: { high_temp: 81, rain: 6 },
      April: { high_temp: 81, rain: 13 },
      May: { high_temp: 80, rain: 14 },
      June: { high_temp: 78, rain: 9 },
      July: { high_temp: 78, rain: 7 },
      August: { high_temp: 78, rain: 6 },
      September: { high_temp: 79, rain: 6 },
      October: { high_temp: 80, rain: 9 },
      November: { high_temp: 80, rain: 11 },
      December: { high_temp: 80, rain: 10 },
    },
  },
  "Venice, Italy": {
    description:
      "A romantic city of canals, gondolas, and historic architecture that feels like stepping into a fairy tale.",
    weather: {
      January: { high_temp: 45, rain: 7 },
      February: { high_temp: 48, rain: 6 },
      March: { high_temp: 56, rain: 7 },
      April: { high_temp: 63, rain: 9 },
      May: { high_temp: 71, rain: 8 },
      June: { high_temp: 78, rain: 7 },
      July: { high_temp: 84, rain: 5 },
      August: { high_temp: 83, rain: 7 },
      September: { high_temp: 76, rain: 7 },
      October: { high_temp: 65, rain: 8 },
      November: { high_temp: 54, rain: 9 },
      December: { high_temp: 46, rain: 8 },
    },
  },
  "London, UK": {
    description:
      "A cosmopolitan capital with historic landmarks, world-class museums, and diverse neighborhoods.",
    weather: {
      January: { high_temp: 47, rain: 10 },
      February: { high_temp: 48, rain: 8 },
      March: { high_temp: 52, rain: 8 },
      April: { high_temp: 57, rain: 8 },
      May: { high_temp: 63, rain: 8 },
      June: { high_temp: 68, rain: 8 },
      July: { high_temp: 72, rain: 8 },
      August: { high_temp: 72, rain: 8 },
      September: { high_temp: 66, rain: 8 },
      October: { high_temp: 59, rain: 10 },
      November: { high_temp: 52, rain: 10 },
      December: { high_temp: 47, rain: 10 },
    },
  },
  "Hong Kong, China": {
    description:
      "A fusion of East and West, with stunning harbor views, bustling markets, and incredible Cantonese cuisine.",
    weather: {
      January: { high_temp: 66, rain: 5 },
      February: { high_temp: 67, rain: 7 },
      March: { high_temp: 71, rain: 9 },
      April: { high_temp: 78, rain: 12 },
      May: { high_temp: 84, rain: 16 },
      June: { high_temp: 88, rain: 18 },
      July: { high_temp: 90, rain: 16 },
      August: { high_temp: 90, rain: 15 },
      September: { high_temp: 87, rain: 13 },
      October: { high_temp: 82, rain: 8 },
      November: { high_temp: 75, rain: 5 },
      December: { high_temp: 68, rain: 4 },
    },
  },
  "Kuala Lumpur, Malaysia": {
    description:
      "A vibrant metropolis famous for the Petronas Towers, diverse street food, and a mix of modern and colonial architecture.",
    weather: {
      January: { high_temp: 88, rain: 13 },
      February: { high_temp: 90, rain: 11 },
      March: { high_temp: 91, rain: 14 },
      April: { high_temp: 92, rain: 16 },
      May: { high_temp: 91, rain: 15 },
      June: { high_temp: 90, rain: 12 },
      July: { high_temp: 90, rain: 13 },
      August: { high_temp: 90, rain: 15 },
      September: { high_temp: 89, rain: 17 },
      October: { high_temp: 89, rain: 19 },
      November: { high_temp: 88, rain: 19 },
      December: { high_temp: 88, rain: 17 },
    },
  },
  "Edinburgh, Scotland": {
    description:
      "A historic city of medieval castles, stunning landscapes, and vibrant arts festivals.",
    weather: {
      January: { high_temp: 40, rain: 19 },
      February: { high_temp: 42, rain: 17 },
      March: { high_temp: 47, rain: 14 },
      April: { high_temp: 52, rain: 12 },
      May: { high_temp: 58, rain: 10 },
      June: { high_temp: 63, rain: 8 },
      July: { high_temp: 66, rain: 8 },
      August: { high_temp: 65, rain: 9 },
      September: { high_temp: 58, rain: 11 },
      October: { high_temp: 50, rain: 15 },
      November: { high_temp: 44, rain: 18 },
      December: { high_temp: 39, rain: 19 },
    },
  },
  "Stockholm, Sweden": {
    description:
      "A city of islands, stunning waterfronts, and Scandinavian elegance.",
    weather: {
      January: { high_temp: 30, rain: 10 },
      February: { high_temp: 32, rain: 8 },
      March: { high_temp: 41, rain: 8 },
      April: { high_temp: 52, rain: 7 },
      May: { high_temp: 63, rain: 8 },
      June: { high_temp: 70, rain: 9 },
      July: { high_temp: 73, rain: 10 },
      August: { high_temp: 71, rain: 10 },
      September: { high_temp: 62, rain: 9 },
      October: { high_temp: 50, rain: 10 },
      November: { high_temp: 39, rain: 10 },
      December: { high_temp: 32, rain: 11 },
    },
  },
  "Denver, Colorado, USA": {
    description:
      "A mile-high city with outdoor adventures, craft breweries, and stunning Rocky Mountain views.",
    weather: {
      January: { high_temp: 45, rain: 4 },
      February: { high_temp: 49, rain: 4 },
      March: { high_temp: 57, rain: 6 },
      April: { high_temp: 61, rain: 7 },
      May: { high_temp: 70, rain: 9 },
      June: { high_temp: 80, rain: 8 },
      July: { high_temp: 88, rain: 10 },
      August: { high_temp: 86, rain: 9 },
      September: { high_temp: 76, rain: 7 },
      October: { high_temp: 64, rain: 6 },
      November: { high_temp: 52, rain: 5 },
      December: { high_temp: 45, rain: 4 },
    },
  },
  "Tokyo, Japan": {
    description:
      "A mesmerizing mix of neon-lit streets, traditional shrines, and world-class dining experiences.",
    weather: {
      January: { high_temp: 48, rain: 5 },
      February: { high_temp: 50, rain: 5 },
      March: { high_temp: 55, rain: 8 },
      April: { high_temp: 65, rain: 9 },
      May: { high_temp: 72, rain: 9 },
      June: { high_temp: 77, rain: 12 },
      July: { high_temp: 83, rain: 11 },
      August: { high_temp: 86, rain: 9 },
      September: { high_temp: 79, rain: 11 },
      October: { high_temp: 69, rain: 9 },
      November: { high_temp: 60, rain: 7 },
      December: { high_temp: 52, rain: 5 },
    },
  },
  "Kyoto, Japan": {
    description:
      "A serene city filled with ancient temples, traditional tea houses, and stunning seasonal cherry blossoms.",
    weather: {
      January: { high_temp: 42, rain: 6 },
      February: { high_temp: 46, rain: 5 },
      March: { high_temp: 53, rain: 7 },
      April: { high_temp: 63, rain: 7 },
      May: { high_temp: 73, rain: 6 },
      June: { high_temp: 78, rain: 12 },
      July: { high_temp: 85, rain: 15 },
      August: { high_temp: 85, rain: 14 },
      September: { high_temp: 77, rain: 10 },
      October: { high_temp: 65, rain: 7 },
      November: { high_temp: 53, rain: 6 },
      December: { high_temp: 44, rain: 5 },
    },
  },
  "Helsinki, Finland": {
    description:
      "A sleek Nordic capital with stunning waterfronts, innovative design, and a cozy winter charm.",
    weather: {
      January: { high_temp: 27, rain: 15 },
      February: { high_temp: 29, rain: 12 },
      March: { high_temp: 37, rain: 10 },
      April: { high_temp: 47, rain: 9 },
      May: { high_temp: 58, rain: 9 },
      June: { high_temp: 67, rain: 9 },
      July: { high_temp: 71, rain: 10 },
      August: { high_temp: 68, rain: 11 },
      September: { high_temp: 58, rain: 12 },
      October: { high_temp: 46, rain: 13 },
      November: { high_temp: 36, rain: 14 },
      December: { high_temp: 29, rain: 15 },
    },
  },
  "Vienna, Austria": {
    description:
      "A city of imperial palaces, classical music, and rich coffeehouse culture.",
    weather: {
      January: { high_temp: 38, rain: 9 },
      February: { high_temp: 42, rain: 8 },
      March: { high_temp: 52, rain: 9 },
      April: { high_temp: 61, rain: 9 },
      May: { high_temp: 71, rain: 10 },
      June: { high_temp: 76, rain: 11 },
      July: { high_temp: 80, rain: 9 },
      August: { high_temp: 79, rain: 9 },
      September: { high_temp: 71, rain: 8 },
      October: { high_temp: 59, rain: 8 },
      November: { high_temp: 47, rain: 9 },
      December: { high_temp: 39, rain: 9 },
    },
  },
  "Nairobi, Kenya": {
    description:
      "A dynamic capital offering a gateway to African wildlife, bustling markets, and a rich cultural heritage.",
    weather: {
      January: { high_temp: 77, rain: 6 },
      February: { high_temp: 78, rain: 6 },
      March: { high_temp: 77, rain: 8 },
      April: { high_temp: 76, rain: 13 },
      May: { high_temp: 75, rain: 15 },
      June: { high_temp: 74, rain: 12 },
      July: { high_temp: 74, rain: 9 },
      August: { high_temp: 75, rain: 7 },
      September: { high_temp: 76, rain: 5 },
      October: { high_temp: 76, rain: 7 },
      November: { high_temp: 76, rain: 9 },
      December: { high_temp: 76, rain: 8 },
    },
  },
  "Vancouver, Canada": {
    description:
      "A scenic city nestled between mountains and ocean, offering diverse culture and outdoor activities.",
    weather: {
      January: { high_temp: 41, rain: 14 },
      February: { high_temp: 44, rain: 10 },
      March: { high_temp: 50, rain: 13 },
      April: { high_temp: 56, rain: 11 },
      May: { high_temp: 63, rain: 9 },
      June: { high_temp: 69, rain: 7 },
      July: { high_temp: 74, rain: 5 },
      August: { high_temp: 73, rain: 4 },
      September: { high_temp: 66, rain: 7 },
      October: { high_temp: 54, rain: 12 },
      November: { high_temp: 45, rain: 14 },
      December: { high_temp: 39, rain: 14 },
    },
  },
  "Istanbul, Turkey": {
    description:
      "A mesmerizing blend of East and West, with grand mosques, bustling bazaars, and rich history.",
    weather: {
      January: { high_temp: 48, rain: 18 },
      February: { high_temp: 48, rain: 15 },
      March: { high_temp: 52, rain: 14 },
      April: { high_temp: 61, rain: 11 },
      May: { high_temp: 70, rain: 9 },
      June: { high_temp: 77, rain: 5 },
      July: { high_temp: 82, rain: 4 },
      August: { high_temp: 82, rain: 4 },
      September: { high_temp: 77, rain: 7 },
      October: { high_temp: 68, rain: 10 },
      November: { high_temp: 59, rain: 13 },
      December: { high_temp: 52, rain: 17 },
    },
  },
  "Quito, Ecuador": {
    description:
      "A high-altitude capital with colonial charm, breathtaking Andean views, and rich indigenous culture.",
    weather: {
      January: { high_temp: 65, rain: 8 },
      February: { high_temp: 65, rain: 8 },
      March: { high_temp: 65, rain: 9 },
      April: { high_temp: 65, rain: 10 },
      May: { high_temp: 64, rain: 11 },
      June: { high_temp: 64, rain: 9 },
      July: { high_temp: 64, rain: 8 },
      August: { high_temp: 64, rain: 8 },
      September: { high_temp: 64, rain: 9 },
      October: { high_temp: 64, rain: 10 },
      November: { high_temp: 64, rain: 9 },
      December: { high_temp: 65, rain: 8 },
    },
  },
  "Taipei, Taiwan": {
    description:
      "A bustling city blending night markets, skyscrapers, and ancient temples.",
    weather: {
      January: { high_temp: 63, rain: 9 },
      February: { high_temp: 64, rain: 8 },
      March: { high_temp: 68, rain: 10 },
      April: { high_temp: 74, rain: 10 },
      May: { high_temp: 80, rain: 13 },
      June: { high_temp: 84, rain: 14 },
      July: { high_temp: 88, rain: 13 },
      August: { high_temp: 87, rain: 12 },
      September: { high_temp: 84, rain: 14 },
      October: { high_temp: 77, rain: 12 },
      November: { high_temp: 69, rain: 9 },
      December: { high_temp: 64, rain: 8 },
    },
  },
  "Tromso, Norway": {
    description:
      "A stunning destination famous for its breathtaking natural beauty, vibrant culture, and spectacular northern lights.",
    weather: {
      January: { high_temp: 27, rain: 22 },
      February: { high_temp: 28, rain: 19 },
      March: { high_temp: 30, rain: 17 },
      April: { high_temp: 34, rain: 14 },
      May: { high_temp: 41, rain: 14 },
      June: { high_temp: 50, rain: 12 },
      July: { high_temp: 55, rain: 14 },
      August: { high_temp: 54, rain: 16 },
      September: { high_temp: 46, rain: 18 },
      October: { high_temp: 36, rain: 21 },
      November: { high_temp: 30, rain: 22 },
      December: { high_temp: 26, rain: 22 },
    },
  },
  "Melbourne, Australia": {
    description:
      "A cultural hub with world-class coffee, street art, and a lively arts scene.",
    weather: {
      January: { high_temp: 79, rain: 7 },
      February: { high_temp: 81, rain: 6 },
      March: { high_temp: 77, rain: 7 },
      April: { high_temp: 70, rain: 8 },
      May: { high_temp: 61, rain: 9 },
      June: { high_temp: 54, rain: 9 },
      July: { high_temp: 54, rain: 10 },
      August: { high_temp: 56, rain: 9 },
      September: { high_temp: 61, rain: 8 },
      October: { high_temp: 68, rain: 7 },
      November: { high_temp: 73, rain: 7 },
      December: { high_temp: 78, rain: 7 },
    },
  },
  "Amsterdam, Netherlands": {
    description:
      "A city of charming canals, historic houses, world-class museums, and a vibrant cycling culture.",
    weather: {
      January: { high_temp: 43, rain: 11 },
      February: { high_temp: 44, rain: 9 },
      March: { high_temp: 50, rain: 9 },
      April: { high_temp: 57, rain: 8 },
      May: { high_temp: 64, rain: 9 },
      June: { high_temp: 68, rain: 9 },
      July: { high_temp: 72, rain: 9 },
      August: { high_temp: 72, rain: 9 },
      September: { high_temp: 66, rain: 9 },
      October: { high_temp: 57, rain: 10 },
      November: { high_temp: 49, rain: 11 },
      December: { high_temp: 44, rain: 11 },
    },
  },
  "Berlin, Germany": {
    description:
      "A city with a vibrant arts scene, historical significance, and legendary nightlife.",
    weather: {
      January: { high_temp: 37, rain: 11 },
      February: { high_temp: 39, rain: 8 },
      March: { high_temp: 47, rain: 9 },
      April: { high_temp: 57, rain: 8 },
      May: { high_temp: 66, rain: 9 },
      June: { high_temp: 72, rain: 9 },
      July: { high_temp: 76, rain: 9 },
      August: { high_temp: 76, rain: 8 },
      September: { high_temp: 67, rain: 8 },
      October: { high_temp: 55, rain: 8 },
      November: { high_temp: 45, rain: 10 },
      December: { high_temp: 39, rain: 10 },
    },
  },
  "Bergen, Norway": {
    description:
      "A picturesque coastal city with colorful wooden houses, scenic fjords, and a rich maritime heritage.",
    weather: {
      January: { high_temp: 36, rain: 22 },
      February: { high_temp: 38, rain: 20 },
      March: { high_temp: 42, rain: 18 },
      April: { high_temp: 46, rain: 16 },
      May: { high_temp: 53, rain: 15 },
      June: { high_temp: 59, rain: 17 },
      July: { high_temp: 63, rain: 20 },
      August: { high_temp: 62, rain: 21 },
      September: { high_temp: 55, rain: 20 },
      October: { high_temp: 46, rain: 22 },
      November: { high_temp: 40, rain: 22 },
      December: { high_temp: 36, rain: 22 },
    },
  },
  "Singapore, Singapore": {
    description:
      "A futuristic city-state known for its world-class cuisine, stunning skyline, and lush green spaces like Gardens by the Bay.",
    weather: {
      January: { high_temp: 86, rain: 19 },
      February: { high_temp: 87, rain: 13 },
      March: { high_temp: 88, rain: 16 },
      April: { high_temp: 88, rain: 17 },
      May: { high_temp: 88, rain: 17 },
      June: { high_temp: 87, rain: 14 },
      July: { high_temp: 87, rain: 14 },
      August: { high_temp: 87, rain: 15 },
      September: { high_temp: 87, rain: 15 },
      October: { high_temp: 87, rain: 16 },
      November: { high_temp: 86, rain: 19 },
      December: { high_temp: 86, rain: 20 },
    },
  },
  "Belize City, Belize": {
    description:
      "A coastal gateway to the Belize Barrier Reef, ancient Mayan sites, and lush jungles.",
    weather: {
      January: { high_temp: 81, rain: 5 },
      February: { high_temp: 82, rain: 3 },
      March: { high_temp: 84, rain: 3 },
      April: { high_temp: 86, rain: 4 },
      May: { high_temp: 88, rain: 7 },
      June: { high_temp: 88, rain: 14 },
      July: { high_temp: 89, rain: 14 },
      August: { high_temp: 89, rain: 14 },
      September: { high_temp: 88, rain: 15 },
      October: { high_temp: 86, rain: 13 },
      November: { high_temp: 83, rain: 7 },
      December: { high_temp: 81, rain: 5 },
    },
  },
  "Buenos Aires, Argentina": {
    description:
      "A tango-loving city with grand architecture, rich culture, and amazing steaks.",
    weather: {
      January: { high_temp: 84, rain: 9 },
      February: { high_temp: 82, rain: 8 },
      March: { high_temp: 79, rain: 9 },
      April: { high_temp: 72, rain: 8 },
      May: { high_temp: 63, rain: 6 },
      June: { high_temp: 58, rain: 5 },
      July: { high_temp: 58, rain: 5 },
      August: { high_temp: 62, rain: 5 },
      September: { high_temp: 67, rain: 6 },
      October: { high_temp: 73, rain: 8 },
      November: { high_temp: 79, rain: 8 },
      December: { high_temp: 82, rain: 9 },
    },
  },
  "Yosemite National Park, USA": {
    description:
      "A breathtaking national park with towering waterfalls, giant sequoias, and granite cliffs.",
    weather: {
      January: { high_temp: 44, rain: 8 },
      February: { high_temp: 47, rain: 7 },
      March: { high_temp: 53, rain: 8 },
      April: { high_temp: 59, rain: 7 },
      May: { high_temp: 67, rain: 6 },
      June: { high_temp: 76, rain: 4 },
      July: { high_temp: 84, rain: 2 },
      August: { high_temp: 83, rain: 3 },
      September: { high_temp: 75, rain: 4 },
      October: { high_temp: 62, rain: 6 },
      November: { high_temp: 51, rain: 7 },
      December: { high_temp: 44, rain: 8 },
    },
  },
  "Sydney, Australia": {
    description:
      "A vibrant harbor city known for the Sydney Opera House, golden beaches, and laid-back lifestyle.",
    weather: {
      January: { high_temp: 79, rain: 10 },
      February: { high_temp: 79, rain: 9 },
      March: { high_temp: 77, rain: 11 },
      April: { high_temp: 73, rain: 10 },
      May: { high_temp: 68, rain: 10 },
      June: { high_temp: 63, rain: 9 },
      July: { high_temp: 62, rain: 8 },
      August: { high_temp: 64, rain: 8 },
      September: { high_temp: 70, rain: 8 },
      October: { high_temp: 73, rain: 9 },
      November: { high_temp: 76, rain: 9 },
      December: { high_temp: 78, rain: 9 },
    },
  },
  "Zanzibar, Tanzania": {
    description:
      "A paradise island with white-sand beaches, spice markets, and historic Stone Town.",
    weather: {
      January: { high_temp: 88, rain: 8 },
      February: { high_temp: 89, rain: 7 },
      March: { high_temp: 89, rain: 9 },
      April: { high_temp: 88, rain: 15 },
      May: { high_temp: 86, rain: 18 },
      June: { high_temp: 84, rain: 12 },
      July: { high_temp: 84, rain: 7 },
      August: { high_temp: 84, rain: 5 },
      September: { high_temp: 85, rain: 3 },
      October: { high_temp: 87, rain: 4 },
      November: { high_temp: 87, rain: 7 },
      December: { high_temp: 88, rain: 8 },
    },
  },
  "Montevideo, Uruguay": {
    description:
      "A laid-back coastal capital with a rich tango scene and beautiful beaches.",
    weather: {
      January: { high_temp: 83, rain: 7 },
      February: { high_temp: 82, rain: 7 },
      March: { high_temp: 78, rain: 8 },
      April: { high_temp: 72, rain: 8 },
      May: { high_temp: 65, rain: 8 },
      June: { high_temp: 59, rain: 7 },
      July: { high_temp: 58, rain: 7 },
      August: { high_temp: 60, rain: 7 },
      September: { high_temp: 65, rain: 7 },
      October: { high_temp: 71, rain: 8 },
      November: { high_temp: 76, rain: 7 },
      December: { high_temp: 81, rain: 7 },
    },
  },
  "Paris, France": {
    description:
      "A timeless city of romance, iconic landmarks, world-class cuisine, and artistic heritage.",
    weather: {
      January: { high_temp: 45, rain: 10 },
      February: { high_temp: 47, rain: 8 },
      March: { high_temp: 54, rain: 9 },
      April: { high_temp: 59, rain: 9 },
      May: { high_temp: 66, rain: 10 },
      June: { high_temp: 72, rain: 9 },
      July: { high_temp: 75, rain: 8 },
      August: { high_temp: 75, rain: 7 },
      September: { high_temp: 70, rain: 8 },
      October: { high_temp: 59, rain: 10 },
      November: { high_temp: 50, rain: 10 },
      December: { high_temp: 45, rain: 10 },
    },
  },
  "Suva, Fiji": {
    description:
      "A tropical paradise with palm-fringed beaches, crystal-clear waters, and a laid-back island vibe.",
    weather: {
      January: { high_temp: 86, rain: 19 },
      February: { high_temp: 86, rain: 18 },
      March: { high_temp: 86, rain: 19 },
      April: { high_temp: 85, rain: 17 },
      May: { high_temp: 83, rain: 14 },
      June: { high_temp: 81, rain: 9 },
      July: { high_temp: 81, rain: 9 },
      August: { high_temp: 82, rain: 8 },
      September: { high_temp: 83, rain: 9 },
      October: { high_temp: 84, rain: 12 },
      November: { high_temp: 85, rain: 16 },
      December: { high_temp: 86, rain: 18 },
    },
  },
  "Cairo, Egypt": {
    description:
      "A historic city on the Nile, home to the Pyramids of Giza and a vibrant, bustling culture.",
    weather: {
      January: { high_temp: 67, rain: 1 },
      February: { high_temp: 69, rain: 1 },
      March: { high_temp: 74, rain: 1 },
      April: { high_temp: 82, rain: 1 },
      May: { high_temp: 90, rain: 0 },
      June: { high_temp: 95, rain: 0 },
      July: { high_temp: 96, rain: 0 },
      August: { high_temp: 96, rain: 0 },
      September: { high_temp: 92, rain: 0 },
      October: { high_temp: 85, rain: 0 },
      November: { high_temp: 76, rain: 1 },
      December: { high_temp: 68, rain: 1 },
    },
  },
  "Copenhagen, Denmark": {
    description:
      "A stylish capital known for its bike-friendly streets, modern design, and cozy hygge culture.",
    weather: {
      January: { high_temp: 34, rain: 14 },
      February: { high_temp: 35, rain: 12 },
      March: { high_temp: 41, rain: 11 },
      April: { high_temp: 50, rain: 10 },
      May: { high_temp: 59, rain: 9 },
      June: { high_temp: 66, rain: 9 },
      July: { high_temp: 71, rain: 9 },
      August: { high_temp: 70, rain: 10 },
      September: { high_temp: 61, rain: 11 },
      October: { high_temp: 50, rain: 12 },
      November: { high_temp: 41, rain: 13 },
      December: { high_temp: 35, rain: 14 },
    },
  },
  "Tel Aviv, Israel": {
    description:
      "A coastal city with beautiful Mediterranean beaches, vibrant nightlife, and a rich cultural scene.",
    weather: {
      January: { high_temp: 61, rain: 9 },
      February: { high_temp: 61, rain: 8 },
      March: { high_temp: 64, rain: 6 },
      April: { high_temp: 70, rain: 4 },
      May: { high_temp: 77, rain: 3 },
      June: { high_temp: 84, rain: 1 },
      July: { high_temp: 88, rain: 0 },
      August: { high_temp: 88, rain: 0 },
      September: { high_temp: 84, rain: 1 },
      October: { high_temp: 75, rain: 3 },
      November: { high_temp: 66, rain: 5 },
      December: { high_temp: 61, rain: 7 },
    },
  },
  "Perth, Australia": {
    description:
      "A sun-drenched coastal city known for beautiful beaches, vibrant nightlife, and access to nature.",
    weather: {
      January: { high_temp: 85, rain: 2 },
      February: { high_temp: 85, rain: 2 },
      March: { high_temp: 82, rain: 3 },
      April: { high_temp: 74, rain: 5 },
      May: { high_temp: 66, rain: 7 },
      June: { high_temp: 60, rain: 9 },
      July: { high_temp: 58, rain: 9 },
      August: { high_temp: 59, rain: 9 },
      September: { high_temp: 64, rain: 8 },
      October: { high_temp: 71, rain: 6 },
      November: { high_temp: 77, rain: 4 },
      December: { high_temp: 82, rain: 3 },
    },
  },
  "Antalya, Turkey": {
    description:
      "A Turkish Riviera gem, offering stunning beaches, ancient ruins, and charming old-town streets.",
    weather: {
      January: { high_temp: 58, rain: 12 },
      February: { high_temp: 59, rain: 11 },
      March: { high_temp: 64, rain: 10 },
      April: { high_temp: 70, rain: 7 },
      May: { high_temp: 79, rain: 4 },
      June: { high_temp: 88, rain: 1 },
      July: { high_temp: 92, rain: 0 },
      August: { high_temp: 92, rain: 0 },
      September: { high_temp: 86, rain: 2 },
      October: { high_temp: 75, rain: 6 },
      November: { high_temp: 64, rain: 9 },
      December: { high_temp: 58, rain: 11 },
    },
  },
  "Valletta, Malta": {
    description:
      "A fortified city with stunning architecture, crystal-clear waters, and a rich history.",
    weather: {
      January: { high_temp: 57, rain: 10 },
      February: { high_temp: 58, rain: 8 },
      March: { high_temp: 61, rain: 8 },
      April: { high_temp: 64, rain: 6 },
      May: { high_temp: 70, rain: 5 },
      June: { high_temp: 77, rain: 3 },
      July: { high_temp: 83, rain: 1 },
      August: { high_temp: 83, rain: 2 },
      September: { high_temp: 79, rain: 4 },
      October: { high_temp: 70, rain: 6 },
      November: { high_temp: 63, rain: 8 },
      December: { high_temp: 57, rain: 9 },
    },
  },
  "Zion National Park, USA": {
    description:
      "A breathtaking natural wonder known for its towering red cliffs, scenic hiking trails, and stunning canyon views.",
    weather: {
      January: { high_temp: 56, rain: 5 },
      February: { high_temp: 58, rain: 4 },
      March: { high_temp: 64, rain: 5 },
      April: { high_temp: 73, rain: 4 },
      May: { high_temp: 83, rain: 4 },
      June: { high_temp: 94, rain: 1 },
      July: { high_temp: 99, rain: 6 },
      August: { high_temp: 97, rain: 7 },
      September: { high_temp: 88, rain: 5 },
      October: { high_temp: 73, rain: 4 },
      November: { high_temp: 61, rain: 5 },
      December: { high_temp: 55, rain: 5 },
    },
  },
  "Boston, Massachusetts, USA": {
    description:
      "A city of American history, elite universities, and charming New England vibes.",
    weather: {
      January: { high_temp: 36, rain: 12 },
      February: { high_temp: 39, rain: 9 },
      March: { high_temp: 47, rain: 10 },
      April: { high_temp: 57, rain: 10 },
      May: { high_temp: 67, rain: 9 },
      June: { high_temp: 76, rain: 8 },
      July: { high_temp: 82, rain: 8 },
      August: { high_temp: 81, rain: 8 },
      September: { high_temp: 74, rain: 9 },
      October: { high_temp: 60, rain: 11 },
      November: { high_temp: 49, rain: 12 },
      December: { high_temp: 39, rain: 12 },
    },
  },
  "Ljubljana, Slovenia": {
    description:
      "A picturesque city with green spaces, a castle on a hill, and a relaxed atmosphere.",
    weather: {
      January: { high_temp: 34, rain: 11 },
      February: { high_temp: 37, rain: 9 },
      March: { high_temp: 45, rain: 9 },
      April: { high_temp: 54, rain: 9 },
      May: { high_temp: 63, rain: 8 },
      June: { high_temp: 73, rain: 7 },
      July: { high_temp: 79, rain: 6 },
      August: { high_temp: 78, rain: 6 },
      September: { high_temp: 67, rain: 7 },
      October: { high_temp: 54, rain: 8 },
      November: { high_temp: 42, rain: 10 },
      December: { high_temp: 35, rain: 11 },
    },
  },
  "Acadia National Park, USA": {
    description:
      "A coastal gem with rocky shores, lush forests, and stunning views of the Atlantic Ocean.",
    weather: {
      January: { high_temp: 28, rain: 9 },
      February: { high_temp: 30, rain: 8 },
      March: { high_temp: 37, rain: 10 },
      April: { high_temp: 47, rain: 11 },
      May: { high_temp: 58, rain: 12 },
      June: { high_temp: 67, rain: 11 },
      July: { high_temp: 74, rain: 9 },
      August: { high_temp: 73, rain: 8 },
      September: { high_temp: 64, rain: 10 },
      October: { high_temp: 51, rain: 12 },
      November: { high_temp: 39, rain: 10 },
      December: { high_temp: 30, rain: 9 },
    },
  },
  "Beijing, China": {
    description:
      "A historic capital home to the Great Wall, the Forbidden City, and the lively hutong alleyways.",
    weather: {
      January: { high_temp: 35, rain: 2 },
      February: { high_temp: 41, rain: 2 },
      March: { high_temp: 55, rain: 3 },
      April: { high_temp: 70, rain: 5 },
      May: { high_temp: 81, rain: 7 },
      June: { high_temp: 88, rain: 10 },
      July: { high_temp: 90, rain: 15 },
      August: { high_temp: 87, rain: 12 },
      September: { high_temp: 79, rain: 7 },
      October: { high_temp: 67, rain: 5 },
      November: { high_temp: 50, rain: 3 },
      December: { high_temp: 38, rain: 2 },
    },
  },
  "Warsaw, Poland": {
    description:
      "A resilient city with a reconstructed Old Town, vibrant cultural scene, and delicious pierogi.",
    weather: {
      January: { high_temp: 30, rain: 9 },
      February: { high_temp: 32, rain: 8 },
      March: { high_temp: 41, rain: 9 },
      April: { high_temp: 50, rain: 9 },
      May: { high_temp: 61, rain: 10 },
      June: { high_temp: 70, rain: 11 },
      July: { high_temp: 74, rain: 11 },
      August: { high_temp: 73, rain: 10 },
      September: { high_temp: 63, rain: 9 },
      October: { high_temp: 50, rain: 9 },
      November: { high_temp: 37, rain: 8 },
      December: { high_temp: 30, rain: 9 },
    },
  },
  "San Francisco, USA": {
    description:
      "A picturesque city with Golden Gate Bridge views, cable cars, and a rich tech scene.",
    weather: {
      January: { high_temp: 58, rain: 10 },
      February: { high_temp: 61, rain: 9 },
      March: { high_temp: 63, rain: 8 },
      April: { high_temp: 66, rain: 5 },
      May: { high_temp: 68, rain: 3 },
      June: { high_temp: 70, rain: 1 },
      July: { high_temp: 70, rain: 0 },
      August: { high_temp: 71, rain: 0 },
      September: { high_temp: 72, rain: 1 },
      October: { high_temp: 70, rain: 3 },
      November: { high_temp: 64, rain: 6 },
      December: { high_temp: 58, rain: 9 },
    },
  },
  "Dublin, Ireland": {
    description:
      "A charming capital of literary legends, cozy pubs, and historic castles.",
    weather: {
      January: { high_temp: 46, rain: 14 },
      February: { high_temp: 47, rain: 11 },
      March: { high_temp: 51, rain: 11 },
      April: { high_temp: 56, rain: 10 },
      May: { high_temp: 60, rain: 10 },
      June: { high_temp: 65, rain: 10 },
      July: { high_temp: 67, rain: 10 },
      August: { high_temp: 67, rain: 11 },
      September: { high_temp: 63, rain: 10 },
      October: { high_temp: 56, rain: 12 },
      November: { high_temp: 50, rain: 13 },
      December: { high_temp: 46, rain: 14 },
    },
  },
  "Cancún, Mexico": {
    description:
      "A tropical paradise known for its white-sand beaches, turquoise waters, and lively nightlife.",
    weather: {
      January: { high_temp: 81, rain: 6 },
      February: { high_temp: 82, rain: 5 },
      March: { high_temp: 84, rain: 5 },
      April: { high_temp: 86, rain: 4 },
      May: { high_temp: 88, rain: 7 },
      June: { high_temp: 89, rain: 11 },
      July: { high_temp: 90, rain: 11 },
      August: { high_temp: 90, rain: 12 },
      September: { high_temp: 89, rain: 15 },
      October: { high_temp: 87, rain: 12 },
      November: { high_temp: 84, rain: 8 },
      December: { high_temp: 82, rain: 6 },
    },
  },
  "Mexico City, Mexico": {
    description:
      "A dynamic capital with ancient Aztec sites, vibrant art, and incredible food.",
    weather: {
      January: { high_temp: 72, rain: 1 },
      February: { high_temp: 75, rain: 1 },
      March: { high_temp: 79, rain: 2 },
      April: { high_temp: 81, rain: 3 },
      May: { high_temp: 82, rain: 9 },
      June: { high_temp: 78, rain: 17 },
      July: { high_temp: 75, rain: 17 },
      August: { high_temp: 76, rain: 16 },
      September: { high_temp: 74, rain: 15 },
      October: { high_temp: 74, rain: 8 },
      November: { high_temp: 73, rain: 3 },
      December: { high_temp: 71, rain: 1 },
    },
  },
  "Christchurch, New Zealand": {
    description:
      "A city of gardens, art, and adventure, with access to stunning natural landscapes.",
    weather: {
      January: { high_temp: 70, rain: 8 },
      February: { high_temp: 71, rain: 6 },
      March: { high_temp: 69, rain: 6 },
      April: { high_temp: 64, rain: 7 },
      May: { high_temp: 57, rain: 8 },
      June: { high_temp: 52, rain: 9 },
      July: { high_temp: 51, rain: 9 },
      August: { high_temp: 53, rain: 8 },
      September: { high_temp: 57, rain: 8 },
      October: { high_temp: 61, rain: 9 },
      November: { high_temp: 64, rain: 8 },
      December: { high_temp: 68, rain: 8 },
    },
  },
  "Anchorage, Alaska, USA": {
    description:
      "A wilderness city with glaciers, wildlife, and stunning northern lights displays.",
    weather: {
      January: { high_temp: 18, rain: 10 },
      February: { high_temp: 20, rain: 8 },
      March: { high_temp: 28, rain: 8 },
      April: { high_temp: 36, rain: 7 },
      May: { high_temp: 46, rain: 6 },
      June: { high_temp: 58, rain: 6 },
      July: { high_temp: 63, rain: 7 },
      August: { high_temp: 61, rain: 8 },
      September: { high_temp: 51, rain: 9 },
      October: { high_temp: 35, rain: 10 },
      November: { high_temp: 23, rain: 11 },
      December: { high_temp: 16, rain: 11 },
    },
  },
};

export default DestinationWeather;
